//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _01.PhotographyDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public Equipment()
        {
            this.PhotographsEnquipments = new HashSet<Photograph>();
            this.UsersEnquipment = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public Nullable<int> LensId { get; set; }
        public int CameraId { get; set; }
    
        public virtual Camera Camera { get; set; }
        public virtual Lens Lens { get; set; }
        public virtual ICollection<Photograph> PhotographsEnquipments { get; set; }
        public virtual ICollection<User> UsersEnquipment { get; set; }
    }
}
