-- MySQL Script generated by MySQL Workbench
-- 06/25/15 11:57:43
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema university
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `university` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `university` ;

-- -----------------------------------------------------
-- Table `university`.`faculties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`faculties` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university`.`deparments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`deparments` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `faculties_id` INT NOT NULL,
  PRIMARY KEY (`id`, `faculties_id`),
  INDEX `fk_deparments_faculties1_idx` (`faculties_id` ASC),
  CONSTRAINT `fk_deparments_faculties1`
    FOREIGN KEY (`faculties_id`)
    REFERENCES `university`.`faculties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '			';


-- -----------------------------------------------------
-- Table `university`.`professors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`professors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `deparments_id` INT NOT NULL,
  PRIMARY KEY (`id`, `deparments_id`),
  INDEX `fk_professors_deparments1_idx` (`deparments_id` ASC),
  CONSTRAINT `fk_professors_deparments1`
    FOREIGN KEY (`deparments_id`)
    REFERENCES `university`.`deparments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`courses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `deparment_id` INT NOT NULL,
  `professors_id` INT NOT NULL,
  PRIMARY KEY (`id`, `deparment_id`, `professors_id`),
  INDEX `fk_courses_deparments1_idx` (`deparment_id` ASC),
  INDEX `fk_courses_professors1_idx` (`professors_id` ASC),
  CONSTRAINT `fk_courses_deparments1`
    FOREIGN KEY (`deparment_id`)
    REFERENCES `university`.`deparments` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_courses_professors1`
    FOREIGN KEY (`professors_id`)
    REFERENCES `university`.`professors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university`.`students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`students` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `faculties_id` INT NOT NULL,
  PRIMARY KEY (`id`, `faculties_id`),
  INDEX `fk_students_faculties1_idx` (`faculties_id` ASC),
  CONSTRAINT `fk_students_faculties1`
    FOREIGN KEY (`faculties_id`)
    REFERENCES `university`.`faculties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university`.`titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`titles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `professors_id` INT NOT NULL,
  PRIMARY KEY (`id`, `professors_id`),
  INDEX `fk_titles_professors1_idx` (`professors_id` ASC),
  CONSTRAINT `fk_titles_professors1`
    FOREIGN KEY (`professors_id`)
    REFERENCES `university`.`professors` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `university`.`courses_and_students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `university`.`courses_and_students` (
  `students_id` INT NOT NULL,
  `courses_id` INT NOT NULL,
  PRIMARY KEY (`students_id`, `courses_id`),
  INDEX `fk_courses_and_students_courses1_idx` (`courses_id` ASC),
  CONSTRAINT `fk_courses_and_students_students1`
    FOREIGN KEY (`students_id`)
    REFERENCES `university`.`students` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_courses_and_students_courses1`
    FOREIGN KEY (`courses_id`)
    REFERENCES `university`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
