//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _01.PhotographyDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Albums = new HashSet<Album>();
            this.PhotographsUser = new HashSet<Photograph>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string FullName { get; set; }
        public System.DateTime BirthDate { get; set; }
        public Nullable<int> EquipmentId { get; set; }
    
        public virtual ICollection<Album> Albums { get; set; }
        public virtual Equipment EquipmentUser { get; set; }
        public virtual ICollection<Photograph> PhotographsUser { get; set; }
    }
}
