CREATE TABLE WorkHours(
	Id INT PRIMARY KEY IDENTITY NOT NULL,
	DateTask DATETIME NOT NULL,
	Task NVARCHAR(50) NOT NULL,
	HoursTask SMALLINT NOT NULL,
	Comment NTEXT NULL,
	EmployeeId INT FOREIGN KEY REFERENCES Employees(EmployeeId) 
)