//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _01.PhotographyDatabaseFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Camera
    {
        public Camera()
        {
            this.EquipmentsCamera = new HashSet<Equipment>();
        }
    
        public int Id { get; set; }
        public int ManufacturerId { get; set; }
        public string Model { get; set; }
        public int Year { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Megapixels { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual ICollection<Equipment> EquipmentsCamera { get; set; }
    }
}
